[2025-05-17 23:25:54,295] INFO in __init__: 应用已启动
[2025-05-17 23:25:54,295] INFO in __init__: 应用已启动
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "/home/taoli/NIDS_ByTaoLi/backend/run.py", line 13, in <module>
    app.run(host='0.0.0.0', port=5000, debug=True)
  File "/home/taoli/.local/lib/python3.10/site-packages/flask/app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/taoli/.local/lib/python3.10/site-packages/werkzeug/serving.py", line 991, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
